MatchingTranslations:
  enabled: false
TemplateLength:
  enabled: false
SchemaJsonFormat:
  enabled: true
  start_level: 0
  indent: '    '
UnusedSnippet:
  enabled: true
NestedSnippet:
  enabled: false
  ignore: []
  max_nesting_level: 8